.github/workflows/pr.yml, package.json, src/App.test.js
Another low hanging fruit that we might wanna automate and opt in sooner rather than later.
=> ci: Add lint task and workflow for linting on pr

.prettierrc.json, src/App.js, src/App.test.js, src/i18n.js, src/index.js, src/reportWebVitals.js, src/setupTests.js
*Context*
#26 
*Changelog*
- Add the proposed prettier config
- Apply the new formatting rules to unchanged files since the pre-commit hook only applies formatting to staged/changed files
=> feat: add prettier config

src/App.js
=> Add ability to direct link to your ID via id query param

README.md, src/App.js, src/locales/en/translations.js
**Why**
Thanks to @dbredvick for checking with the DevRel team to help us get sponsorship with Vercel
We need to add a vercel banner in the site and read to meet the Sponsorship Criteria https://vercel.com/support/articles/can-vercel-sponsor-my-open-source-project
**What changed**
- Add vercel banner in the footer 
- Add vercel banner in the README.md
=> Add Vercel sponsorship info

README.md
=> Fixed README.md logo

src/i18n.js, src/locales/zhsc/translations.js, src/locales/zhtc/translations.js
Added both traditional and simplified Chinese translation.
=> Added chinese translation

src/components/Footer/index.js
=> Changed footer github url

.all-contributorsrc, README.md, src/pages/index.js
Context — #43 
The query param — NFT ID integration was broken for some reason (try visiting https://www.developerdao.com/?id=5350). The problem was that `router.query.id` was coming up as `undefined` on the first render & hence the variable `id` was defaulting to `1`.
~~To fix this, I switched from static site generation to SSR (you cannot get query params from the server in SSG because the page is...well, static. It's only rendered once, at build time).~~ Everything now works.
=> feat: sync URL state with current NFT ID

src/components/Footer/index.js
=> refactor: GitHub format

package.json, public/locales/en/common.json, src/pages/index.js, src/utils/DeveloperDaoConstants.js, yarn.lock
Context: #44 
I added [Chakra UI's package for icons](https://chakra-ui.com/docs/media-and-icons/icon) too since I think we'll need to use these icons in the future as the project grows.
=> feat: add 'copy link to nft' button

README.md
Been a good week since we moved on from CRA & Tailwind, people
=> fix: Update outdated tech stack & misc in readme

public/locales/zh-CN/common.json, public/locales/zh-HK/common.json, public/locales/zh-TW/common.json, public/locales/zh/common.json
Sorry for (myself) missing the updates recently, so busy with a new position in berlin orz
- Update chinese family translation with missing keys
- Using `$t(title)` translation
- I updated some naming (e.g. `name` -> `開發者DAO`) due to the growthing complexity in wordings... please amend or discuss with you are feeling weird on the chinese wordings!
`zh` - Language Settings: `Chinese` or  `zh-cn` - Language Settings: `Chinese (Simplified)`:
`zh-hk` - Language Settings:`Chinese (Hong Kong)` or `zh-tw` - Language Settings: `Chinese (Traditional)`
Relating to issues: #88, #95, #118
=> Updated chinese family translation

docs/CONTRIBUTING.md
Fixes some grammatical errors in docs.
N/A
N/A
N/A
N/A
=> fix: Grammatical errors in docs

_tests_/pages/mint.test.jsx, src/utils/DeveloperDaoConstants.ts
Modified link to point to https://developerdao.vercel.app/ for available token search.
Closes #153
=> Modified Token Search Link to point to app with filtering option

package.json, src/components/Nav/index.tsx, yarn.lock
**Navbar is responsive now. Photos below show the navbar menu becoming responsive at smaller breakpoints.   ** 
Let me know if how my code looks. Would love feedback
=> responsive navbar

next-i18next.config.js
Fixes issue with potential build issues on Vercel having to do with localePaths being missing
This was a long standing issue that only got recently resolved in a previous issue that was closed due to a change in direction of the website.  This is a necessary change for future localized paths that may end up on the site
N/A
N/A
N/A
Closes #...
=> Adds localPath fix to address missing locale issues on build

public/locales/en/common.json
Changing a word in the callout body
Changing a word in the callout section
We think the word is Inappropriate especially in cases like when we show the website to philanthropists asking for D_D grants
No
No
No
Closes #...
=> Changing a word in the callout section

public/locales/en/common.json, src/pages/index.tsx
It adds a link to the DevDAO blog and the corresponding English translation.
=> Add link to blog

src/Components/Header/index.tsx, src/layout/Page/index.tsx
Adds new Header component with initial layout, sizes, padding and margin. These props may need adjusting once the other components are merged.
**Any helpful background information?**
[Discord Chat](https://discord.com/channels/883478451850473483/884852584941232169/946474631760601098)
No
Relevant screenshots
Draft PR #207
=> Header component

src/Components/Footer/index.tsx, src/Components/Header/index.tsx, src/layout/Page/index.tsx
Adds new footer component
[Discord Chat](https://discord.com/channels/883478451850473483/884852584941232169/946474631760601098)
No
Closes #206
=> Add Footer component

public/locales/en/common.json, src/Components/Values/index.tsx, src/theme.ts, src/utils/DeveloperDaoConstants.ts
Adds the Values component. It contains the DAO's values, mission and goals. It also contains a link to the wiki.
[Discord discussion](https://discord.com/channels/883478451850473483/884852584941232169/946494436429430824)
No
Closes #210
=> Add the Values section

src/Components/Footer/index.tsx, src/Components/Header/index.tsx
Removes the variant usage in some places for now.
The variants previously had no effect due to a config issue. The issue was fixed in #212 and the ones that were left changed the intended design.
No
Closes #218
=> Fix font sizes

src/Components/Footer/index.tsx, src/Components/Header/index.tsx, src/Components/Intro/index.tsx, src/Components/Partners/index.tsx, src/Components/Values/index.tsx
- Cleanup resources
- Add marquee
- Add header
- Add background color in `theme.ts`
- Add Components
- Increase divider size
- Header component (#214)
- Add Footer component (#211)
- add intro component (#217)
- Fix `flexDirection` for intro component
- Add the Values section (#212)
- Remove variant definitions from `theme.ts` for now. (#223)
- Remove unused imports
- Add partners section (#222)
- add url to the `href` in links
- Update `Layout` structure
- Rename blur-img-light.svg to Blur-img-light.svg
- Add url to the links
- Update index.tsx
- Update styling for the partners button
- Remove unused assets
- Various padding / margin updates to intro component to better match values
- Partners top / bottom padding to match design
- Update partners button padding to match design
- Clean …
=> component-blending

public/locales/zh-CN/common.json, public/locales/zh-HK/common.json, public/locales/zh-TW/common.json
Update Translation of CN HK TW. I found the previous trans is out of date.
CN translation is done by DAO member Alex1237#2487, HK and TW are done by DAO member jimxjim.eth
No
No
No
Closes #...
=> Update Translation of CN, HK, TW

.all-contributorsrc, src/Components/Footer/index.tsx, src/Components/Partners/index.tsx
Change partner form to updated Airtable form
Closes #242
=> adding airtable partner enquiry form

public/locales/zh-CN/common.json, public/locales/zh-HK/common.json, public/locales/zh-TW/common.json, public/locales/zh/common.json
Update CN HK TW Translation for this branch
What is the difference between zh and zh-cn?
None
none
Closes #...
=> Update CN HK TW Translation

.env.development, .env.production, .gitignore, package.json, src/Components/Partners/index.tsx, src/pages/index.tsx, yarn.lock
This is a DRAFT PR for integrating Strapi into the FE of the website. So far @mhmulford0 and I integrated the data fetching from the CMS for the Partners component on the home page.
Work on this PR needs to be done in parralel with updates to the content model on the CMS.
- Apollo
- Graphql
Closes #...
=> Integrating Strapi CMS

src/Components/Partners/index.tsx
=> Partner image fix
